require "../spec_helper"

describe SSH::PublicKey do
  describe ".parse_ed25519" do
    it "parses a key generated by PrivateKey.generate" do
      _, pub_line = SSH::PrivateKey.generate("my-comment")
      key = SSH::PublicKey.parse_ed25519(pub_line)
      key.key_bytes.size.should eq(32)
      key.comment.should eq("my-comment")
    end

    it "raises on wrong key type" do
      expect_raises(Exception, /not an Ed25519/) do
        SSH::PublicKey.parse_ed25519("ssh-rsa AAAAB3NzaC1yc2EAAAA comment")
      end
    end

    it "raises on malformed base64" do
      expect_raises(Exception, /invalid base64/) do
        SSH::PublicKey.parse_ed25519("ssh-ed25519 not!!valid!!base64 comment")
      end
    end

    it "raises when line has too few fields" do
      expect_raises(Exception, /expected at least 2 fields/) do
        SSH::PublicKey.parse_ed25519("ssh-ed25519")
      end
    end
  end
end
